version: '3.8'
services:
  telegraf:
    build: .
    container_name: telegraf
    restart: unless-stopped
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc:/host/etc:ro
      - /mnt/nas-data-4:/mnt/nas-data-4:ro
      - /mnt/nas-2-fast-data-2:/mnt/nas-2-fast-data-2:ro
    env_file:
      - .env
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_ETC=/host/etc
    network_mode: host
